import AppKit
import Foundation

protocol PasteboardReading {
    var changeCount: Int { get }
    var typeIdentifiers: [String] { get }
    func readString() -> String?
    func readFileURLs() -> [URL]
}

struct SystemPasteboardReader: PasteboardReading {
    var changeCount: Int { NSPasteboard.general.changeCount }

    var typeIdentifiers: [String] {
        (NSPasteboard.general.types ?? []).map(\.rawValue)
    }

    func readString() -> String? {
        NSPasteboard.general.string(forType: .string)
    }

    func readFileURLs() -> [URL] {
        let objects = NSPasteboard.general.readObjects(
            forClasses: [NSURL.self], options: [.urlReadingFileURLsOnly: true]
        ) as? [URL]
        return objects ?? []
    }
}

@MainActor
final class ClipboardHistoryMonitor {
    static let skippedTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        ClipboardImageMonitor.selfWriteMarker.rawValue,
    ]

    private static let pollInterval: TimeInterval = 0.5

    private let store: ClipboardHistoryStore
    private let reader: PasteboardReading
    private var timer: Timer?
    private var lastChangeCount: Int

    init(store: ClipboardHistoryStore, reader: PasteboardReading = SystemPasteboardReader()) {
        self.store = store
        self.reader = reader
        lastChangeCount = reader.changeCount
    }

    func start() {
        guard timer == nil else { return }
        lastChangeCount = reader.changeCount
        let timer = Timer(timeInterval: Self.pollInterval, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated { self?.poll() }
        }
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
        Log.clipboard.info("Clipboard history monitor started")
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    func poll() {
        let changeCount = reader.changeCount
        guard changeCount != lastChangeCount else { return }
        lastChangeCount = changeCount

        let types = Set(reader.typeIdentifiers)
        guard types.isDisjoint(with: Self.skippedTypes) else { return }

        let fileURLs = reader.readFileURLs()
        if !fileURLs.isEmpty {
            for url in fileURLs.prefix(10) {
                store.ingestFile(path: url.path)
            }
            return
        }
        guard let string = reader.readString() else { return }
        store.ingest(string)
    }
}
